<?php
$nomServeur="localhost";
$loginAdminServeur="root";
$motPasseAdminServeur="root";
$nomBaseDonnee="icofsiosuivi";
$prefixeTable="port_";
$crypte=false;
$smtp=false;
$melContact="tiphaine.accary-barbier@icof.fr";
$lngmdp=8;
?>