<?php
$nomServeur="mysql5-16.pro";
$loginAdminServeur="icofsiosuivi";
$motPasseAdminServeur="icof2012";
$nomBaseDonnee="icofsiosuivi";
$prefixeTable="port_";
$crypte=false;
$smtp=false;
$melContact="tiphaine.accary-barbier@icof.fr";
$lngmdp=8;
?>